function validate_config(cfg)
%VALIDATE_CONFIG Fail early on nonphysical or unsupported inputs.

    assert(cfg.structure.Nz >= 50, 'Nz must be at least 50.');
    assert(cfg.structure.n_states >= 2, 'At least two states are required.');
    assert(cfg.structure.Lz_nm > 0, 'Lz must be positive.');
    assert(cfg.structure.U0_meV > 0, 'U0 must be positive.');
    assert(isfinite(cfg.structure.manning_prefactor), ...
        'Manning prefactor must be finite.');
    assert(cfg.temperature_K > 0, 'Temperature must be positive.');
    assert(cfg.doping.Nd_sheet_cm2 >= 0, 'Sheet density cannot be negative.');
    assert(cfg.oap.Nqz >= 8 && cfg.oap.Nqperp >= 8, ...
        'q grids are too small.');
    assert(all(diff(cfg.oap.photon_energy_meV) > 0), ...
        'Photon-energy grid must be strictly increasing.');
    assert(size(cfg.oap.transitions, 2) == 2, ...
        'cfg.oap.transitions must have two columns [initial final].');
    assert(all(cfg.oap.transitions(:) >= 1), ...
        'Transition indices are MATLAB 1-based and must be >= 1.');
    assert(max(cfg.oap.transitions(:)) <= cfg.structure.n_states, ...
        'A transition index exceeds structure.n_states.');
    assert(all(cfg.oap.photon_orders >= 1), ...
        'Photon orders must be positive integers.');
    assert(all(cfg.oap.photon_orders == round(cfg.oap.photon_orders)), ...
        'Photon orders must be integers.');
    assert(any(strcmpi(cfg.oap.q_model, {'source_qperp','generalized_3d'})), ...
        'oap.q_model must be source_qperp or generalized_3d.');
    assert(cfg.oap.Nkin_perp >= 8 && cfg.oap.fermi_tail_kBT > 0, ...
        'In-plane delta integration controls are invalid.');
    if strcmpi(cfg.laser.a0_mode, 'dynamic')
        assert(all(cfg.oap.photon_energy_meV > 0), ...
            'Dynamic a0 requires strictly positive photon energies.');
    end
    if any(cfg.oap.photon_orders >= 3)
        warning('QW:PhotonOrderExtrapolation', [ ...
            'Photon orders >= 3 are extrapolations; the supplied ', ...
            'source derivation validates only orders [1 2].']);
    end
    if isfield(cfg.structure, 'alpha') && any(isfinite(cfg.structure.alpha(:)))
        error('QW:UnsupportedAlpha', [ ...
            'cfg.structure.alpha is unsupported by the Manning/sech ', ...
            'potential. Use cfg.structure.manning_prefactor instead.']);
    end
end
