function validate_config(cfg)
%VALIDATE_CONFIG Fail early on nonphysical or unsupported inputs.

    assert(cfg.structure.Nz >= 50, 'Nz must be at least 50.');
    assert(cfg.structure.n_states >= 2, 'At least two states are required.');
    assert(cfg.structure.Lz_nm > 0, 'Lz must be positive.');
    assert(cfg.structure.U0_meV > 0, 'U0 must be positive.');
    assert(cfg.temperature_K > 0, 'Temperature must be positive.');
    assert(cfg.doping.Nd_sheet_cm2 >= 0, 'Sheet density cannot be negative.');
    assert(cfg.oap.Nqz >= 8 && cfg.oap.Nqperp >= 8, ...
        'q grids are too small.');
    assert(all(diff(cfg.oap.photon_energy_meV) > 0), ...
        'Photon-energy grid must be strictly increasing.');
    assert(size(cfg.oap.transitions, 2) == 2, ...
        'cfg.oap.transitions must have two columns [initial final].');
    assert(all(cfg.oap.transitions(:) >= 1), ...
        'Transition indices are MATLAB 1-based and must be >= 1.');
    assert(max(cfg.oap.transitions(:)) <= cfg.structure.n_states, ...
        'A transition index exceeds structure.n_states.');
    assert(all(cfg.oap.photon_orders >= 1), ...
        'Photon orders must be positive integers.');

    if strcmpi(cfg.oap.model, 'direct_q_integral')
        orders = cfg.oap.photon_orders(:).';
        if any(orders ~= round(orders)) || any(~ismember(orders, [1 2]))
            error('QW:DirectPhotonOrder', ...
                ['direct_q_integral is derived only for photon orders ', ...
                 'ell = 1 and 2.']);
        end
        if strcmpi(cfg.laser.a0_mode, 'dynamic') && ...
                any(~isfinite(cfg.oap.photon_energy_meV) | ...
                    cfg.oap.photon_energy_meV <= 0)
            error('QW:DirectPhotonEnergy', ...
                'Dynamic a0 requires strictly positive photon energies.');
        end
    end

    if strcmpi(cfg.oap.model, 'analytical_series')
        orders = cfg.oap.photon_orders(:).';
        if any(orders ~= round(orders)) || any(~ismember(orders, [1 2]))
            error('QW:AnalyticalPhotonOrder', ...
                ['analytical_series implements only photon orders ell = ', ...
                 '1 and 2 according to Eq. (5)/(7).']);
        end
        if strcmpi(cfg.laser.a0_mode, 'dynamic') && ...
                any(~isfinite(cfg.oap.photon_energy_meV) | ...
                    cfg.oap.photon_energy_meV <= 0)
            error('QW:AnalyticalPhotonEnergy', ...
                'Dynamic a0 requires strictly positive photon energies.');
        end
        if ~(isscalar(cfg.oap.normalization_area_m2) && ...
                isfinite(cfg.oap.normalization_area_m2) && ...
                cfg.oap.normalization_area_m2 > 0)
            error('QW:AnalyticalNormalizationArea', ...
                'normalization_area_m2 must be finite and positive.');
        end
        if ~(isscalar(cfg.oap.series.s_max) && ...
                isfinite(cfg.oap.series.s_max) && ...
                cfg.oap.series.s_max >= 1 && ...
                cfg.oap.series.s_max == round(cfg.oap.series.s_max)) || ...
                ~(isscalar(cfg.oap.series.eta_max) && ...
                  isfinite(cfg.oap.series.eta_max) && ...
                  cfg.oap.series.eta_max >= 0 && ...
                  cfg.oap.series.eta_max == round(cfg.oap.series.eta_max))
            error('QW:AnalyticalSeriesTruncation', ...
                'series.s_max >= 1 and series.eta_max >= 0 must be integers.');
        end
    end
end
