function validate_config(cfg)
%VALIDATE_CONFIG Fail early on nonphysical or unsupported inputs.

    assert(cfg.structure.Nz >= 50, 'Nz must be at least 50.');
    assert(cfg.structure.n_states >= 2, 'At least two states are required.');
    assert(cfg.structure.Lz_nm > 0, 'Lz must be positive.');
    assert(cfg.structure.U0_meV > 0, 'U0 must be positive.');
    assert(cfg.temperature_K > 0, 'Temperature must be positive.');
    assert(cfg.doping.Nd_sheet_cm2 >= 0, 'Sheet density cannot be negative.');
    assert(cfg.oap.Nqz >= 8 && cfg.oap.Nqperp >= 8, ...
        'q grids are too small.');
    photon_energy_meV = cfg.oap.photon_energy_meV;
    assert(isnumeric(photon_energy_meV) && isvector(photon_energy_meV) && ...
        ~isempty(photon_energy_meV) && isreal(photon_energy_meV) && ...
        all(isfinite(photon_energy_meV)), ...
        'Photon-energy grid must be a nonempty finite real vector.');
    assert(all(diff(photon_energy_meV) > 0), ...
        'Photon-energy grid must be strictly increasing.');
    assert(size(cfg.oap.transitions, 2) == 2, ...
        'cfg.oap.transitions must have two columns [initial final].');
    assert(all(cfg.oap.transitions(:) >= 1), ...
        'Transition indices are MATLAB 1-based and must be >= 1.');
    assert(max(cfg.oap.transitions(:)) <= cfg.structure.n_states, ...
        'A transition index exceeds structure.n_states.');
    assert(all(cfg.oap.photon_orders >= 1), ...
        'Photon orders must be positive integers.');

    model = lower(cfg.oap.model);
    if ismember(model, {'van','analytical_series','analytic_series','nhan'})
        if any(photon_energy_meV == 0)
            error('QW:ZeroPhotonEnergy', ...
                ['The Van/Nhan PDF formulas are singular at exactly ', ...
                 'hbar*Omega = 0. Negative energies are supported, but ', ...
                 'a grid spanning both signs must omit the zero point.']);
        end
        orders = cfg.oap.photon_orders(:).';
        if any(orders ~= round(orders)) || any(~ismember(orders,[1 2])) || ...
                numel(unique(orders)) ~= numel(orders)
            error('QW:AnalyticalPhotonOrder', ...
                'The selected PDF model requires unique photon orders 1 and 2.');
        end
        assert(isscalar(cfg.oap.normalization_area_m2) && ...
            isfinite(cfg.oap.normalization_area_m2) && ...
            cfg.oap.normalization_area_m2 > 0, ...
            'normalization_area_m2 must be finite and positive.');
    end
    if strcmp(model,'nhan')
        if ~(isscalar(cfg.oap.series.s_max) && ...
                isfinite(cfg.oap.series.s_max) && ...
                cfg.oap.series.s_max >= 1 && ...
                cfg.oap.series.s_max == round(cfg.oap.series.s_max)) || ...
                ~(isscalar(cfg.oap.series.eta_max) && ...
                  isfinite(cfg.oap.series.eta_max) && ...
                  cfg.oap.series.eta_max >= 0 && ...
                  cfg.oap.series.eta_max == round(cfg.oap.series.eta_max))
            error('QW:NhanSeriesTruncation', ...
                'series.s_max>=1 and series.eta_max>=0 must be integers.');
        end
    end
end
