function save_case_outputs(case_result, cfg, tag, figures)
%SAVE_CASE_OUTPUTS Save MAT, CSV and figures for one case.

    ensure_directory(cfg.output.directory);


    safe_tag = regexprep( ...
        tag, ...
        '[^A-Za-z0-9_-]', ...
        '_');


    % ================================================================
    % MAT
    % ================================================================
    if cfg.output.save_mat

        save(fullfile(cfg.output.directory, [safe_tag '.mat']), 'case_result', '-v7.3');

    end

    % ================================================================
    % CSV spectrum
    % ================================================================
    if cfg.output.save_csv

        E = case_result.spectrum.energy_meV(:);

        total = case_result.spectrum.total_raw(:);

        optical = case_result.spectrum.mechanism.optical.total_raw(:);

        piezo = case_result.spectrum.mechanism.piezoelectric.total_raw(:);

        T = table( ...
            E, ...
            total, ...
            optical, ...
            piezo, ...
            'VariableNames', { ...
                'PhotonEnergy_meV', ...
                'TotalRaw', ...
                'OpticalRaw', ...
                'PiezoelectricRaw' ...
            });


        writetable( ...
            T, ...
            fullfile( ...
                cfg.output.directory, ...
                [safe_tag '_spectrum.csv']));


        write_metrics_csv( ...
            case_result.metrics, ...
            cfg, ...
            fullfile( ...
                cfg.output.directory, ...
                [safe_tag '_metrics.csv']));

    end


    % ================================================================
    % Figures
    % ================================================================
    if cfg.output.save_figures

        names = { ...
            'structure', ...
            'spectrum_optical', ...
            'spectrum_piezoelectric', ...
            'contributions_optical', ...
            'contributions_piezoelectric' ...
        };


        nfig = min( ...
            numel(figures), ...
            numel(names));


        for i = 1:nfig

            if ishghandle(figures{i})

                filename = fullfile( ...
                    cfg.output.directory, ...
                    [ ...
                        safe_tag, ...
                        '_', ...
                        names{i}, ...
                        '.', ...
                        cfg.output.figure_format ...
                    ]);


                export_figure_compat( ...
                    figures{i}, ...
                    filename, ...
                    cfg.output.figure_dpi);

            end

        end

    end

end